*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZVTO_PARAM06....................................*
FORM GET_DATA_ZVTO_PARAM06.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTO_PARAM03 WHERE
(VIM_WHERETAB) .
    CLEAR ZVTO_PARAM06 .
ZVTO_PARAM06-MANDT =
ZTO_PARAM03-MANDT .
ZVTO_PARAM06-DEVID =
ZTO_PARAM03-DEVID .
ZVTO_PARAM06-PARAM =
ZTO_PARAM03-PARAM .
ZVTO_PARAM06-SYSNAME =
ZTO_PARAM03-SYSNAME .
ZVTO_PARAM06-NUMER =
ZTO_PARAM03-NUMER .
ZVTO_PARAM06-VALWH =
ZTO_PARAM03-VALWH .
ZVTO_PARAM06-VALTH =
ZTO_PARAM03-VALTH .
ZVTO_PARAM06-VALTH2 =
ZTO_PARAM03-VALTH2 .
<VIM_TOTAL_STRUC> = ZVTO_PARAM06.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVTO_PARAM06 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVTO_PARAM06.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVTO_PARAM06-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTO_PARAM03 WHERE
  DEVID = ZVTO_PARAM06-DEVID AND
  PARAM = ZVTO_PARAM06-PARAM AND
  SYSNAME = ZVTO_PARAM06-SYSNAME AND
  NUMER = ZVTO_PARAM06-NUMER .
    IF SY-SUBRC = 0.
    DELETE ZTO_PARAM03 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTO_PARAM03 WHERE
  DEVID = ZVTO_PARAM06-DEVID AND
  PARAM = ZVTO_PARAM06-PARAM AND
  SYSNAME = ZVTO_PARAM06-SYSNAME AND
  NUMER = ZVTO_PARAM06-NUMER .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTO_PARAM03.
    ENDIF.
ZTO_PARAM03-MANDT =
ZVTO_PARAM06-MANDT .
ZTO_PARAM03-DEVID =
ZVTO_PARAM06-DEVID .
ZTO_PARAM03-PARAM =
ZVTO_PARAM06-PARAM .
ZTO_PARAM03-SYSNAME =
ZVTO_PARAM06-SYSNAME .
ZTO_PARAM03-NUMER =
ZVTO_PARAM06-NUMER .
ZTO_PARAM03-VALWH =
ZVTO_PARAM06-VALWH .
ZTO_PARAM03-VALTH =
ZVTO_PARAM06-VALTH .
ZTO_PARAM03-VALTH2 =
ZVTO_PARAM06-VALTH2 .
    IF SY-SUBRC = 0.
    UPDATE ZTO_PARAM03 ##WARN_OK.
    ELSE.
    INSERT ZTO_PARAM03 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVTO_PARAM06-UPD_FLAG,
STATUS_ZVTO_PARAM06-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVTO_PARAM06.
  SELECT SINGLE * FROM ZTO_PARAM03 WHERE
DEVID = ZVTO_PARAM06-DEVID AND
PARAM = ZVTO_PARAM06-PARAM AND
SYSNAME = ZVTO_PARAM06-SYSNAME AND
NUMER = ZVTO_PARAM06-NUMER .
ZVTO_PARAM06-MANDT =
ZTO_PARAM03-MANDT .
ZVTO_PARAM06-DEVID =
ZTO_PARAM03-DEVID .
ZVTO_PARAM06-PARAM =
ZTO_PARAM03-PARAM .
ZVTO_PARAM06-SYSNAME =
ZTO_PARAM03-SYSNAME .
ZVTO_PARAM06-NUMER =
ZTO_PARAM03-NUMER .
ZVTO_PARAM06-VALWH =
ZTO_PARAM03-VALWH .
ZVTO_PARAM06-VALTH =
ZTO_PARAM03-VALTH .
ZVTO_PARAM06-VALTH2 =
ZTO_PARAM03-VALTH2 .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVTO_PARAM06 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVTO_PARAM06-DEVID TO
ZTO_PARAM03-DEVID .
MOVE ZVTO_PARAM06-PARAM TO
ZTO_PARAM03-PARAM .
MOVE ZVTO_PARAM06-SYSNAME TO
ZTO_PARAM03-SYSNAME .
MOVE ZVTO_PARAM06-NUMER TO
ZTO_PARAM03-NUMER .
MOVE ZVTO_PARAM06-MANDT TO
ZTO_PARAM03-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTO_PARAM03'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTO_PARAM03 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTO_PARAM03'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
