*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZVTO_PARAM01....................................*
FORM GET_DATA_ZVTO_PARAM01.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTO_PARAM01 WHERE
(VIM_WHERETAB) .
    CLEAR ZVTO_PARAM01 .
ZVTO_PARAM01-MANDT =
ZTO_PARAM01-MANDT .
ZVTO_PARAM01-DEVID =
ZTO_PARAM01-DEVID .
ZVTO_PARAM01-PARAM =
ZTO_PARAM01-PARAM .
ZVTO_PARAM01-SYSNAME =
ZTO_PARAM01-SYSNAME .
ZVTO_PARAM01-ROLNM =
ZTO_PARAM01-ROLNM .
ZVTO_PARAM01-PARTY =
ZTO_PARAM01-PARTY .
ZVTO_PARAM01-DESPA =
ZTO_PARAM01-DESPA .
<VIM_TOTAL_STRUC> = ZVTO_PARAM01.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVTO_PARAM01 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVTO_PARAM01.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVTO_PARAM01-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTO_PARAM01 WHERE
  DEVID = ZVTO_PARAM01-DEVID AND
  PARAM = ZVTO_PARAM01-PARAM AND
  SYSNAME = ZVTO_PARAM01-SYSNAME .
    IF SY-SUBRC = 0.
    DELETE ZTO_PARAM01 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTO_PARAM01 WHERE
  DEVID = ZVTO_PARAM01-DEVID AND
  PARAM = ZVTO_PARAM01-PARAM AND
  SYSNAME = ZVTO_PARAM01-SYSNAME .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTO_PARAM01.
    ENDIF.
ZTO_PARAM01-MANDT =
ZVTO_PARAM01-MANDT .
ZTO_PARAM01-DEVID =
ZVTO_PARAM01-DEVID .
ZTO_PARAM01-PARAM =
ZVTO_PARAM01-PARAM .
ZTO_PARAM01-SYSNAME =
ZVTO_PARAM01-SYSNAME .
ZTO_PARAM01-ROLNM =
ZVTO_PARAM01-ROLNM .
ZTO_PARAM01-PARTY =
ZVTO_PARAM01-PARTY .
ZTO_PARAM01-DESPA =
ZVTO_PARAM01-DESPA .
    IF SY-SUBRC = 0.
    UPDATE ZTO_PARAM01 ##WARN_OK.
    ELSE.
    INSERT ZTO_PARAM01 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVTO_PARAM01-UPD_FLAG,
STATUS_ZVTO_PARAM01-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVTO_PARAM01.
  SELECT SINGLE * FROM ZTO_PARAM01 WHERE
DEVID = ZVTO_PARAM01-DEVID AND
PARAM = ZVTO_PARAM01-PARAM AND
SYSNAME = ZVTO_PARAM01-SYSNAME .
ZVTO_PARAM01-MANDT =
ZTO_PARAM01-MANDT .
ZVTO_PARAM01-DEVID =
ZTO_PARAM01-DEVID .
ZVTO_PARAM01-PARAM =
ZTO_PARAM01-PARAM .
ZVTO_PARAM01-SYSNAME =
ZTO_PARAM01-SYSNAME .
ZVTO_PARAM01-ROLNM =
ZTO_PARAM01-ROLNM .
ZVTO_PARAM01-PARTY =
ZTO_PARAM01-PARTY .
ZVTO_PARAM01-DESPA =
ZTO_PARAM01-DESPA .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVTO_PARAM01 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVTO_PARAM01-DEVID TO
ZTO_PARAM01-DEVID .
MOVE ZVTO_PARAM01-PARAM TO
ZTO_PARAM01-PARAM .
MOVE ZVTO_PARAM01-SYSNAME TO
ZTO_PARAM01-SYSNAME .
MOVE ZVTO_PARAM01-MANDT TO
ZTO_PARAM01-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTO_PARAM01'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTO_PARAM01 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTO_PARAM01'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
